#!/bin/sh

DATE=`date +%Y-%m-%d`
DIR="/Library/Webserver/Documents/site"
SQL="$DIR/$DATE.sql"
LOG="$DIR/static/bash/log"
DB_USER="username"
DB_PASS="password"
DB_HOST="example.com"
DB_NAME="databasename"
DB_USER_LOCAL="username"
DB_PASS_LOCAL="password"
DB_HOST_LOCAL="localhost"
DB_NAME_LOCAL="databasename_local"
WWW_USER="username"
WWW_HOST="example.com"

echo "\nStart mysql ..."
echo "\n$DATE" >>$LOG
mysqldump -u $DB_USER -p$DB_PASS -h $DB_HOST $DB_NAME > $SQL 2>>$LOG
mysql -u $DB_USER_LOCAL -p$DB_PASS_LOCAL $DB_NAME_LOCAL < $SQL 2>>$LOG
echo "\nStart rsync ..."
rsync -azP $WWW_USER@$WWW_HOST:/var/www/html/media/ $DIR/media 2>>$LOG
rm $SQL
